[package]
name = "WinDebloaterOfficial"
version = "2.0.0"
edition = "2021"
description = "Herramienta CLI para optimizar Windows eliminando bloatware y mejorando privacidad"
authors = ["Oscar"]

[dependencies]
colored = "2"
anyhow = "1"
